### ISSUE TITLE
Comparison to dag-factory or boundary-layer

### ISSUE THREAD

**Issue by Jaikant** [chriscardillo/gusty#10]
The project looks great!

I have been searching for something just like this, I also came across other a little older projects which do similar things.

dag-factory - [https://github.com/ajbosco/dag-factory](https://github.com/ajbosco/dag-factory)

boundary-layer - [https://github.com/etsy/boundary-layer](https://github.com/etsy/boundary-layer)

Is there a comparison between the three of them. I am looking for something light and feature rich but it should also be extensible in the future.

**Comment by chriscardillo** [comment]
Hello Jai! Thanks so much for taking an interest in gusty.

I would say the main difference between dag-factory and gusty is that (to the best of my understanding) dag-factory requires the entire DAG to be represented in a single YAML file, while gusty believes in a one-task-per-YAML-file approach. The only other difference I am aware of is that since gusty takes a per-file approach to tasks, we also support reading in YAML front matter from `.ipynb` and `.Rmd` files, which means that - as illustrated in the [demo repo](https://github.com/chriscardillo/gusty-demo/blob/master/airflow/operators/jupyter_operator.py) - you can pretty quickly get to a place where you are rendering notebooks in your data pipeline.

The short answer is that gusty's goal is for you to have a manageable folder of tasks (and metadata) for your DAG/task groups, which automatically materialize in Airflow, so that you can focus on other parts of your Airflow implementation.
 
As of gusty 0.3.0, which I just pushed to the master branch here and plan to release on PyPi today, all of this functionality will be provided in a single `create_dag` function which you can learn much more about in the readme. My hope is that gusty 0.3.0 is intuitive and provides a desired level of flexibility, but mostly stays out of your way after you initially set it up.

In terms of future plans, in a later release I want to support sensors in addition to operators, and I want to create more functionality around a DAG's root dependencies, e.g. if one DAG but wait on an entire other DAG, or a single sensor, that should be able to be specified in the DAG's metadata (though the DAG-waits-on-another-DAG functionality is currently possible if you put all of your tasks in a single task group and have that task group depend on another DAG).

Please let me know if you have any other questions in terms of setting up Airflow with gusty,  and I apologize for the breaking change of using `create_dag` instead of `GustyDAG` in 0.3.0, but the good news is you just have to replace `GustyDAG` with `create_dag` and everything else should work the same!

**Comment by Jaikant** [comment]
This sounds really awesome! Thanks for the wonderful work.
